### ISSUE TITLE
Grades for Midyear CMSC 2

### ISSUE THREAD

**Issue by tjmonsi** [tjmonsi/simple-node-server#1]
Contest your grade by writing a comment below. We will re-run the auto-correct system and see if there are changes. All grades will be final by July 27 5pm. If you didn't submit any comment to correct the grade, the grade posted will be final.
1. https://github.com/UdzzM/simple-node-server 
   - **Grade: 1.0**
2. https://github.com/aldainetalan/simple-node-server 
   - DO AUTOCORRECT should have /third-subproject/ file:
   - DO AUTOCORRECT should have bootstrap, foundation or materialize
   - **Grade: 2.0**
3. https://github.com/annekristine/simple-node-server (CORRECTED)
   - DO AUTOCORRECT should have bootstrap, foundation or materialize
   - **Grade: 1.5**
4. https://github.com/atcammayo/simple-node-server
   - No files inside
   - **Grade: INC**
5. https://github.com/caquillo/simple-node-server (CORRECTED)
   - **Grade: 1.0**
6. https://github.com/cfdungca/simple-node-server
   - **Grade: 1.0**
7. https://github.com/ch3rish/simple-node-server
   - **Grade: 1.0**
8. https://github.com/din110/simple-node-server
   - No files
   - **Grade: INC**
9. https://github.com/emilybanares/simple-node-server
   - No files
   - **Grade: INC**
10. https://github.com/erickasombillo/simple-node-server
    - DO AUTOCORRECT should have /modern-internet/
    - **Grade: INC**
11. https://github.com/hanntesoro/simple-node-server (CORRECTED)
    - DO AUTOCORRECT should have bootstrap, foundation or materialize in /modern-internet/
    - **Grade: 1.5**
12. https://github.com/hanskas12/simple-node-server
    - DO AUTOCORRECT should have /third-subproject/ file:
    - No subprojects
    - **Grade: INC**
13. https://github.com/hnhangeles/simple-node-server
    - **Grade: 1.0**
14. https://github.com/jafjamisola/simple-node-server (CORRECTED)
    - DO AUTOCORRECT should have bootstrap, foundation or materialize in /modern-internet/
    - DO AUTOCORRECT should have /third-subproject/
    - **Grade: 2.0**
15. https://github.com/JeyFilan/simple-node-server
    - Missing files
    - DO AUTOCORRECT should have /history-of-the-internet/
    - DO AUTOCORRECT should have /modern-internet/ files
    - DO AUTOCORRECT should have /third-subproject/
    - **Grade: INC**
16. https://github.com/jocazayrand/simple-node-server
    - **Grade: 1.0**
17. https://github.com/jonasetv/simple-node-server
    - DO AUTOCORRECT should have /third-subproject/ file
    - DO AUTOCORRECT should have /history-of-the-internet/
    - DO AUTOCORRECT should have /modern-internet/
    - Missing files
    - **Grade: INC**
18. https://github.com/julesluna/simple-node-server (CORRECTED)
    - DO AUTOCORRECT should have /third-subproject/
    - **Grade: 1.5**
19. https://github.com/justinneaudrey/simple-node-server
    - DO AUTOCORRECT should have /history-of-the-internet/
    - DO AUTOCORRECT should have /modern-internet/
    - DO AUTOCORRECT should have /third-subproject/
    - **Grade: INC**
20. https://github.com/karoooool/simple-node-server
    - **Grade: 1.0**
21. https://github.com/katecambel/simple-node-server
    - **Grade: 1.0**
22. https://github.com/keizelminorka/simple-node-server
    - DO AUTOCORRECT should have /third-subproject/ file
    - DO AUTOCORRECT should have bootstrap, foundation or materialize in /modern-internet/
    - **Grade: 2.0**
23. https://github.com/kristinecas/simple-node-server
    - No files
    - **Grade: INC**
24. https://github.com/ksmacaro/simple-node-server
    - DO AUTOCORRECT should have /history-of-the-internet/
    - DO AUTOCORRECT should have /modern-internet/
    - DO AUTOCORRECT should have /third-subproject/
    - **Grade: INC**
25. https://github.com/KylaLavalle/simple-node-server
    - DO AUTOCORRECT should have /history-of-the-internet/
    - DO AUTOCORRECT should have /modern-internet/
    - DO AUTOCORRECT should have /third-subproject/
    - **Grade: INC**
26. https://github.com/leafatimaysabel/simple-node-server
    - DO AUTOCORRECT should have /third-subproject/
    - DO AUTOCORRECT should have a javascript source /modern-internet/
    - **Grade: 2.5**
27. https://github.com/ManzanoKing/simple-node-server
    - **Grade: 1.0**
28. https://github.com/miggymiranda/simple-node-server
    - DO AUTOCORRECT should have /modern-internet/
    - DO AUTOCORRECT should have /third-subproject/
    - **Grade: INC**
29. https://github.com/ndbautista/simple-node-server
    - **Grade: 1.0**
30. https://github.com/nkyrstnn/simple-node-server (CORRECTED)
    - DO AUTOCORRECT should have /third-subproject/
    - DO AUTOCORRECT should have bootstrap, foundation or materialize
    - **Grade: 2.0**
31. https://github.com/pgmjose/simple-node-server
    - DO AUTOCORRECT should have /third-subproject/
    - DO AUTOCORRECT should have bootstrap, foundation or materialize in /modern-internet/
    - **Grade: 2.0**
32. https://github.com/RussellManzanares/simple-node-server (CORRECTED)
    - DO AUTOCORRECT should have bootstrap, foundation or materialize in /modern-internet/
    - DO AUTOCORRECT should have /third-subproject/
    - **Grade: 2.0**
33. https://github.com/RuthAlcantara23/simple-node-server (CORRECTED)
    - DO AUTOCORRECT should have /third-subproject/
    - DO AUTOCORRECT should have bootstrap, foundation or materialize in /modern-internet/
    - **Grade: 2.0**
34. https://github.com/rvevangelista21/simple-node-server (CORRECTED)
    - **Grade: 1.0**
35. https://github.com/ryseline/simple-node-server
    - DO AUTOCORRECT should have /third-subproject/
    - **Grade: 1.5**
36. https://github.com/shirubiah/simple-node-server
    - No files
    - **Grade: INC**
37. https://github.com/tishambal/simple-node-server
    - DO AUTOCORRECT should have bootstrap, foundation or materialize in /modern-internet/
    - **Grade: 1.5**
38. https://github.com/tjtenedero/simple-node-server
    - No files
    - **Grade: INC**
39. https://github.com/VickyMay/simple-node-server
    - DO AUTOCORRECT should have /third-subproject/
    - DO AUTOCORRECT should have bootstrap, foundation or materialize in /modern-internet/
    - **Grade: 2.0**
40. https://github.com/VRequiron/simple-node-server
    - No files
    - **Grade: INC**

**Comment by nkyrstnn** [comment]
Sir, complete b po ba ito? wala po kasi ung akin

**Comment by tjmonsi** [comment]
Di pa ako tapos.. Nahigit ako sa children's party

**Comment by tishambal** [comment]
Sir wala po akin :(

**Comment by tishambal** [comment]
Ay sorry po di ko po nakita yung comment nyo sa taas.

**Comment by jafjamisola** [comment]
sir sorry po, di ko po nakitang nag-error po pala sa pag-push ko last night, na-push ko na po ngayon. and regarding the third subproject, kasama po ba siya sa requirements? i thought po kasi optional lang siya. thanks po.

**Comment by tjmonsi** [comment]
Optional sya... nilalabas ko lang yung errors nung auto-correct system ko

**Comment by tjmonsi** [comment]
@jafjamisola - edited your grade

**Comment by jafjamisola** [comment]
thank you po, sir!

**Comment by tjmonsi** [comment]
@nkyrstnn Kaya mo pa bang magpush ng bagong commit para mapataas grade mo?

**Comment by annekristine** [comment]
sir, meron po akong subproject3 pero iba lg yung file name. Kailangan ko po bang ire-name yung file for subproject 3?

**Comment by tjmonsi** [comment]
Please re-name it as /third-subproject/ and put it in public folder

**Comment by tjmonsi** [comment]
@annekristine anyway, just saw it and had your grade corrected :)

**Comment by annekristine** [comment]
thanks sir :) na re-name and pinush ko na po ulit

**Comment by annekristine** [comment]
Sir, magrereflect po ba yung corrected grade dito sa post? Hindi pa po kasi napapalitan. Sorry po sa abala :)

**Comment by tjmonsi** [comment]
@annekristine: thanks for the headsup. I put it on the wrong area

**Comment by miggymiranda** [comment]
Sir, hanggang kelan po pwede icomplete yung mga project? Thank you po!

**Comment by tjmonsi** [comment]
Monday 4pm

**Comment by tjmonsi** [comment]
@miggymiranda you are now currently tracked. :)

**Comment by julesluna** [comment]
Sir! Kakapush ko lang po ng 2nd project. Pasa na po ba ko?

**Comment by tjmonsi** [comment]
@julesluna kulang ka pa isang file... Hello World ng Javascript exercises

**Comment by julesluna** [comment]
Ay opo pala sige po teka lang po. Sorry po

**Comment by julesluna** [comment]
@tjmonsi Sir na push ko na din po un java script po! <3

**Comment by RussellManzanares** [comment]
Hi sir, na update ko na po yung kulang sa modern-internet. Pero yung sa history-of-the-internet na push ko na po before the deadline.

**Comment by tjmonsi** [comment]
@RussellManzanares

Please follow instructions on how the projects should be put. There's a specific folder and the position of the folder inside the public. If you don't fix it by Monday, it will remain as INC.

/modern-internet 
/history-of-the-internet

folders should be inside /public and not some "Subproject" folder. The instructions are clear... carry them out :)

**Comment by nkyrstnn** [comment]
Hi sir, bakit po sabi sakin kulang ako ng modern internet? Eh complete naman po ung napush ko before deadline. Mali po b ung ginawa ko?

**Comment by tjmonsi** [comment]
@nkyrstnn Saw that one of your files in modern-internet didn't have javascript on it. Please check. But I already changed the grade

**Comment by julesluna** [comment]
@tjmonsi sir sorry po kulit, ano na po grade ko?

**Comment by tjmonsi** [comment]
@julesluna just create the javascript exercise Hello World to just change your grade from INC

**Comment by julesluna** [comment]
@tjmonsi tapos na po sir. Napush ko na po kanina po.

**Comment by tjmonsi** [comment]
@julesluna done

**Comment by julesluna** [comment]
@tjmonsi Sir sobrang thank you po! <3 What a birthday gift! Salamat po sa mga tinuro niyo!

**Comment by tjmonsi** [comment]
@julesluna magpakain ka naman... burger burger burger :hamburger:

**Comment by RussellManzanares** [comment]
Hi sir! Nagawa ko na po yung necessary changes sa relative path. :)

**Comment by julesluna** [comment]
@tjmonsi Sige sir pag nagkita po tayo sa daan! <3 Thank you po ulit!

**Comment by RussellManzanares** [comment]
Pati dun sa maling name na Subproject.

**Comment by rvevangelista21** [comment]
Sir, na lagay ko na po yung kulang ko po. Thanks po Sir!!! :)

**Comment by tjmonsi** [comment]
@RussellManzanares need to do one more thing... please do javascript exercise hello world :)

**Comment by tjmonsi** [comment]
@rvevangelista21 you still have 1 missing file :) - blogging

**Comment by RussellManzanares** [comment]
sir tapos na po. :)

**Comment by rvevangelista21** [comment]
Sige po sir, Wait lang po.

**Comment by tjmonsi** [comment]
@RussellManzanares done :)

**Comment by RussellManzanares** [comment]
Thank you sir! :D

**Comment by rvevangelista21** [comment]
Sir, nalagay ko na po.. :)

**Comment by tjmonsi** [comment]
@rvevangelista21 done :)

**Comment by rvevangelista21** [comment]
Thanks Sir! Salamat nga po pala ulit sa Burger! :)

**Comment by tjmonsi** [comment]
@rvevangelista21 @RussellManzanares @julesluna @nkyrstnn @annekristine @jafjamisola @tishambal Are your friends' grades here as well? Can you guys contact them if their grade is enough? Thanks guys

**Comment by RuthAlcantara23** [comment]
@tjmonsi Hi sir i'm currently working on my subproject. I'll try to re-submit before 4pm tomorrow. Thanks po!

**Comment by ghost** [comment]
https://github.com/hanntesoro/simple-node-server/tree/master/public sir pahabol po ng 3rd subproject :D thank you po! :)

**Comment by RuthAlcantara23** [comment]
@tjmonsi  Sir na-push ko na po bagong commit :) https://github.com/RuthAlcantara23/simple-node-server

**Comment by tjmonsi** [comment]
@hanntesoro done :)

**Comment by tjmonsi** [comment]
@RuthAlcantara23 done :)

**Comment by RuthAlcantara23** [comment]
@tjmonsi sir, may materialize po ako on both subprojects...or mail yung gawa?

**Comment by miggymiranda** [comment]
sir, nag push na po ako ng project po.

**Comment by caquillo** [comment]
Hi Sir, added stuff to my subprojects! https://github.com/caquillo/simple-node-server

**Comment by tjmonsi** [comment]
@miggymiranda Where's your modern internet?

**Comment by tjmonsi** [comment]
@caquillo done :)
